# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: test
      POSTGRES_DB: bikesharing
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
